apiVersion: v1
kind: Service
metadata:
  labels:
    app: feed-api
  name: feed-api-svc
  namespace: default
  selfLink: /api/v1/namespaces/default/services/feed-api-svc
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: feed-api
  type: ClusterIP