apiVersion: v1
kind: Service
metadata:
  name: reverse-proxy-svc
  labels:
    app: reverse-proxy
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    app: reverse-proxy
  type: LoadBalancer